# File: OpenDocSeal/infrastructure/kube/API-Persistentvolumeclaim.yaml
# Version: 1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendocseal-api-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: opendocseal-api-local-pv
  storageClassName: ""
